### ISSUE TITLE
Investigate problem with long query

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2113]
### Context

As stated in [this document](https://docs.google.com/document/d/1NxduveG7tTI_IVZVhlZD_bHedm9XEoklt-3mvya4LzQ/edit#bookmark=id.vqfgk1qhyy9i) Andrew ran into a problem with a long SQL query while using CARTO.js. The same query ran with no problems in Builder.

Investigate what is happening there.

**Comment by andrewbt** [comment]
Thanks for documenting this one for me @ivanmalagon - I got started trying to "Steps to Reproduce" it fully and got sidetracked on other projects. I'll show what I have so far here.

Dataset used: https://team.carto.com/u/athompson/dataset/athompson.cartodbjs_sql_test

This is the query that is having problems:
```sql
select 1 as cartodb_id, 'route line' as description, ST_MakeLine(
  ST_Centroid((SELECT the_geom from cartodbjs_sql_test where cartodb_id = 1)),
  ST_Centroid((SELECT the_geom from cartodbjs_sql_test where cartodb_id = 2))
  ) as the_geom,
  ST_Transform((ST_MakeLine(
  ST_Centroid((SELECT the_geom from cartodbjs_sql_test where cartodb_id = 1)),
  ST_Centroid((SELECT the_geom from cartodbjs_sql_test where cartodb_id = 2))
  )), 4326) as the_geom_webmercator
```

That was the query that I made at the event and tested in Builder. It works in Builder, in the sense that in the Dataset view it will return a row without errors, with a line connecting the two centroids of the two polygons in the original table. The odd thing is that I cannot get this query to _render_ on the map in Builder (or CARTO.js) in either the Preview or other map views.

I don't think it will render in CartoDB.js version 3, either (but there are no errors in the console! silent failure!), as tested in @ramiroaznar 's "basic viewer": http://bl.ocks.org/ramiroaznar/raw/5a10c324dd0f4230f20db75b671a3eda/ with the following CartoCSS:

```css
#layer['mapnik::geometry_type'=1] {
  marker-width: 7;
  marker-fill: #EE4D5A;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFFFFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-allow-overlap: true;
}
#layer['mapnik::geometry_type'=2] {
  line-color: #4CC8A3;
  line-width: 1.5;
  line-opacity: 1;
}
#layer['mapnik::geometry_type'=3] {
  polygon-fill: #826DBA;
  polygon-opacity: 0.9;
  ::outline {
    line-color: #FFFFFF;
    line-width: 1;
    line-opacity: 0.5;
  }
}
```

To get the query to render in Builder, I had to "Create dataset from query" - that then created dataset will render. Makes me wonder if Builder / CARTO.js / Mapnik somewhere is getting cantankerous with the change in geometry type from `point` to `line`. Here's a .carto file with the created dataset:

[Untitled Map 21 (on 2018-05-09 at 17.35.40).carto.zip](https://github.com/CartoDB/carto.js/files/1988847/Untitled.Map.21.on.2018-05-09.at.17.35.40.carto.zip)

After thinking and trying to debug, I made this other query that behaves much better and achieves the desired result:
```sql
with a as (select st_centroid(the_geom_webmercator) as the_geom_webmercator from cartodbjs_sql_test where cartodb_id = 1),
b as (select st_centroid(the_geom_webmercator) as the_geom_webmercator from cartodbjs_sql_test where cartodb_id = 2)
select 1 as cartodb_id, 'route line' as description, st_makeline(a.the_geom_webmercator, b.the_geom_webmercator) as the_geom_webmercator from cartodbjs_sql_test, a, b
```

I tested that query in ramiro's "basic viewer" and so I think it does work in cartodb.js version 3 - I just hadn't gotten to the point where I could test it to CARTO.js v4.

The problem could be in CARTO.js or in the map rendering backend somewhere - not sure.
